### ISSUE TITLE
undefined symbol: gzclose

### ISSUE THREAD

**Issue by eserte** [shlomif/Text-Hspell#1]
The test suite fails on some of my linux smokers:
```
Can't load '/home/cpansand/.cpan/build/2020042916/Text-Hspell-0.2.3-DcZxRC/blib/arch/auto/Text/Hspell/Hspell.so' for module Text::Hspell: /home/cpansand/.cpan/build/2020042916/Text-Hspell-0.2.3-DcZxRC/blib/arch/auto/Text/Hspell/Hspell.so: undefined symbol: gzclose at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
Compilation failed in require at t/check_word.t line 9.
BEGIN failed--compilation aborted at t/check_word.t line 9.
# Looks like your test exited with 255 before it could output anything.
t/check_word.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/3 subtests 
```

Actually it seems that it passes on fedora/centos systems and fails on debian/ubuntu.

**Comment by shlomif** [comment]
Thanks, @eserte ! Please try smoking version 0.2.4.

**Comment by eserte** [comment]
Unfortunately this failure still may happen: http://matrix.cpantesters.org/?dist=Text-Hspell%200.2.4;os=linux;reports=1

**Comment by shlomif** [comment]
@eserte : thanks! Please test with v0.2.5 - tested in an ubuntu 16.04 vm.

**Comment by eserte** [comment]
I think this is resolved now.

**Comment by shlomif** [comment]
Thanks for the update, @eserte ! I guess it is a nice birthday present (5 May).
